# Generated by Django 2.2.13 on 2020-08-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shorts',
        ),
    ]
